# frozen_string_literal: true

require 'togo_var/api/models/version1/base'

require 'togo_var/api/models/version1/alpha_missense'
require 'togo_var/api/models/version1/and'
require 'togo_var/api/models/version1/bool'
require 'togo_var/api/models/version1/cadd_phred'
require 'togo_var/api/models/version1/chromosome'
require 'togo_var/api/models/version1/clinical_significance'
require 'togo_var/api/models/version1/dataset'
require 'togo_var/api/models/version1/disease'
require 'togo_var/api/models/version1/gene'
require 'togo_var/api/models/version1/id'
require 'togo_var/api/models/version1/location'
require 'togo_var/api/models/version1/non_strict_terms'
require 'togo_var/api/models/version1/not_exist'
require 'togo_var/api/models/version1/or'
require 'togo_var/api/models/version1/polyphen'
require 'togo_var/api/models/version1/range'
require 'togo_var/api/models/version1/sift'
require 'togo_var/api/models/version1/sscv_db'
require 'togo_var/api/models/version1/strict_terms'
require 'togo_var/api/models/version1/variant'
require 'togo_var/api/models/version1/variant_consequence'
require 'togo_var/api/models/version1/variant_frequency'
require 'togo_var/api/models/version1/variant_search'
require 'togo_var/api/models/version1/variant_type'
